services:
  nextjs-app:
    image: nextjs-frontend
    container_name: nextjs-frontend
    restart: always
    ports:
      - '3009:3000' #3009 from nginx config
    environment:
      - NODE_ENV=production