import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

import { ProvidersWrapper } from './providersWrapper';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Main title',
    description: 'Generated by create next app',
    openGraph: {
        title: 'Main',
        images: 'https://is-next-seo.netlify.app/test.jpg',
    },
    twitter: {
        title: 'Main',
        images: 'https://is-next-seo.netlify.app/test.jpg',
        card: 'summary_large_image',
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.svg" sizes="any" />

                <meta name="robots" content="index, follow" />

                {/*    
                <!-- описание сайта используется роботами и подставляется в описании к ссылкам в соцсетях -->
                <meta
                    name="description"
                    content=""
                />

                <meta
                    name="keywords"
                    content="voice, coin, voice coin, vote, vote coin, poll, polls, mem, mem-coin, defi, farm, lend, yield, apy, inside, decentralized, crypto, cryptocorrency, invest, investments, passive income"
                />
                <meta
                    property="og:title"
                    content=""
                />
                <meta
                    property="og:description"
                    content=""
                />
                <meta property="og:image:type" content="image/jpeg" />
                <meta property="og:type" content="website" />
                <meta property="og:url" content="https://voice.io" />
                <meta property="og:site_name" content="Voice Coin" /> */}

                {/* Internet Explorer optimization */}
                <meta httpEquiv="x-ua-compatible" content="ie=edge" />
            </head>

            <body className={`${geistSans.variable}`}>
                <ProvidersWrapper>{children}</ProvidersWrapper>
            </body>
        </html>
    );
}
