import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

import { ProvidersWrapper } from './providersWrapper';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Main title',
    description: 'Generated by create next app',
    openGraph: {
        title: 'Main',
        images: 'https://is-next-seo.netlify.app/test.jpg',
    },
    twitter: {
        title: 'Main',
        images: 'https://is-next-seo.netlify.app/test.jpg',
        card: 'summary_large_image',
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable}`}>
                <ProvidersWrapper>{children}</ProvidersWrapper>
            </body>
        </html>
    );
}
